version: 2
# Color of machine gets taken from a prefix of C-xxx or M-xxx
stations:
  C-BS: 
    active: true
    debug: true
    type: BS
    position: MZ18
    orientation: 0
  C-CS1:
    active: true
    debug: true
    type: CS
    position: MZ54
    orientation: 135
  C-CS2:
    active: true
    debug: true
    type: CS
    position: CZ77
    orientation: 90
  C-RS1:
    active: true
    debug: true
    type: RS
    position: CZ21
    orientation: 180
  C-RS2:
    active: true
    debug: true
    type: RS
    position: MZ25
    orientation: 45
  C-DS:
    active: true
    debug: true
    type: DS
    position: MZ72
    orientation: 90
  C-SS:
    active: true
    debug: true
    type: SS
    position: MZ77
    orientation: 270
  M-BS:
    active: true
    debug: true
    type: BS
    position: MZ28
    orientation: 0
  M-CS1:
    active: true
    debug: true
    type: CS
    position: CZ54
    orientation: 45
  M-CS2:
    active: true
    debug: true
    type: CS
    position: CZ47
    orientation: 90
  M-RS1:
    active: true
    debug: true
    type: RS
    position: MZ21
    orientation: 135
  M-RS2:
    active: true
    debug: true
    type: RS
    position: CZ15
    orientation: 180
  M-DS:
    active: true
    debug: true
    type: DS
    position: CZ72
    orientation: 225
  M-SS:
    active: true
    debug: true
    type: SS
    position: MZ78
    orientation: 0
robots:
  Grips1:
    active: true
    jersey: 1
    team: cyan
    connection: udp
  Grips2:
    active: true
    jersey: 2
    team: cyan
    connection: udp
  Grips3:
    active: true
    jersey: 3
    team: cyan
    connection: udp
  Caro1:
    active: true
    jersey: 1
    team: magenta
    connection: udp
  Caro2:
    active: true
    jersey: 2
    team: magenta
    connection: udp
  Caro3:
    active: true
    jersey: 3
    team: magenta
    connection: udp
teams:
  CYAN:
    name: GRIPS
    active: true
    host: 127.0.0.1
    port: 2017
  MAGENTA:
    name: Carologistics
    active: true
    host: 127.0.0.1
    #host: 192.168.2.255
    port: 2016
refbox:
  public:
    ip: 127.0.0.1 # is also used as mqtt broker address
    # The simulation communicates via tcp to get ground-truth
    tcp: 4444
    send: 4445
    recv: 4444
  cyan:
    send: 4446
    recv: 4441
  magenta:
    send: 4442
    recv: 4447
  mqtt:
    broker_ip: 127.0.0.1
    broker_port: 1883
    active: true
webui:
  prefix: http  
  port: 8000
general:
  timefactor: 1.0
  fixed-mps-position: false
  mockup-connections: false
  robot-connection-type: udp  # connection can be UDP and TCP currently. if nothing is given we default to tcp
  ignore-teamcolor: true
  robot-prepare-mps: true # robot is responsible to send prepare machine messages, option might be removed in future as teams tend to send prepare via their main control unit
  robot-direct-beacon: false  # Robot is expected to send his beaconsignals directly to the refbox via udp
  enable-barcode-scanner: true
  robot-move-zone-duration: 2 # in seconds
  robot-grab-product-duration: 10 # duration for a single try of a grab 
  robot-maximum-grab-duration: 40 # duration after which a grab is stopped 
  robot-place-product-duration: 10 # duration for a single place try
  belt-action-duration: 2.5 # time the belt takes to move a product from one place to another - taken from gazebo
  bs-dispense-duration: 2.5 # time the base station takes to dispense a base - taken from gazebo
  cs-buffer-duration: 3.5  # buffer cap - taken from gazebo
  rs-mount-duration: 3.5  # mounting a ring 3.5 seconds - taken from gazebo
  ds-deliver-duration: 3.5  # time it takes to deliver - taken from gazebo
