// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RingInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LlsfMsgs {

  /// <summary>Holder for reflection information generated from RingInfo.proto</summary>
  public static partial class RingInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for RingInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RingInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5SaW5nSW5mby5wcm90bxIJbGxzZl9tc2dzGhJQcm9kdWN0Q29sb3IucHJv",
            "dG8iRgoEUmluZxIoCgpyaW5nX2NvbG9yGAEgAigOMhQubGxzZl9tc2dzLlJp",
            "bmdDb2xvchIUCgxyYXdfbWF0ZXJpYWwYAiACKA0iUgoIUmluZ0luZm8SHgoF",
            "cmluZ3MYASADKAsyDy5sbHNmX21zZ3MuUmluZyImCghDb21wVHlwZRIMCgdD",
            "T01QX0lEENAPEgwKCE1TR19UWVBFEG5CMQofb3JnLnJvYm9jdXBfbG9naXN0",
            "aWNzLmxsc2ZfbXNnc0IOUmluZ0luZm9Qcm90b3M="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::LlsfMsgs.ProductColorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::LlsfMsgs.Ring), global::LlsfMsgs.Ring.Parser, new[]{ "RingColor", "RawMaterial" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LlsfMsgs.RingInfo), global::LlsfMsgs.RingInfo.Parser, new[]{ "Rings" }, null, new[]{ typeof(global::LlsfMsgs.RingInfo.Types.CompType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Ring : pb::IMessage<Ring> {
    private static readonly pb::MessageParser<Ring> _parser = new pb::MessageParser<Ring>(() => new Ring());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Ring> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LlsfMsgs.RingInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Ring() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Ring(Ring other) : this() {
      _hasBits0 = other._hasBits0;
      ringColor_ = other.ringColor_;
      rawMaterial_ = other.rawMaterial_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Ring Clone() {
      return new Ring(this);
    }

    /// <summary>Field number for the "ring_color" field.</summary>
    public const int RingColorFieldNumber = 1;
    private readonly static global::LlsfMsgs.RingColor RingColorDefaultValue = global::LlsfMsgs.RingColor.RingBlue;

    private global::LlsfMsgs.RingColor ringColor_;
    /// <summary>
    /// Ring color this concerns
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::LlsfMsgs.RingColor RingColor {
      get { if ((_hasBits0 & 1) != 0) { return ringColor_; } else { return RingColorDefaultValue; } }
      set {
        _hasBits0 |= 1;
        ringColor_ = value;
      }
    }
    /// <summary>Gets whether the "ring_color" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasRingColor {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "ring_color" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearRingColor() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "raw_material" field.</summary>
    public const int RawMaterialFieldNumber = 2;
    private readonly static uint RawMaterialDefaultValue = 0;

    private uint rawMaterial_;
    /// <summary>
    /// number of additional bases
    /// required to produce this ring type
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint RawMaterial {
      get { if ((_hasBits0 & 2) != 0) { return rawMaterial_; } else { return RawMaterialDefaultValue; } }
      set {
        _hasBits0 |= 2;
        rawMaterial_ = value;
      }
    }
    /// <summary>Gets whether the "raw_material" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasRawMaterial {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "raw_material" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearRawMaterial() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Ring);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Ring other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RingColor != other.RingColor) return false;
      if (RawMaterial != other.RawMaterial) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasRingColor) hash ^= RingColor.GetHashCode();
      if (HasRawMaterial) hash ^= RawMaterial.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (HasRingColor) {
        output.WriteRawTag(8);
        output.WriteEnum((int) RingColor);
      }
      if (HasRawMaterial) {
        output.WriteRawTag(16);
        output.WriteUInt32(RawMaterial);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasRingColor) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RingColor);
      }
      if (HasRawMaterial) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RawMaterial);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Ring other) {
      if (other == null) {
        return;
      }
      if (other.HasRingColor) {
        RingColor = other.RingColor;
      }
      if (other.HasRawMaterial) {
        RawMaterial = other.RawMaterial;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RingColor = (global::LlsfMsgs.RingColor) input.ReadEnum();
            break;
          }
          case 16: {
            RawMaterial = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RingInfo : pb::IMessage<RingInfo> {
    private static readonly pb::MessageParser<RingInfo> _parser = new pb::MessageParser<RingInfo>(() => new RingInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RingInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LlsfMsgs.RingInfoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RingInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RingInfo(RingInfo other) : this() {
      rings_ = other.rings_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RingInfo Clone() {
      return new RingInfo(this);
    }

    /// <summary>Field number for the "rings" field.</summary>
    public const int RingsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::LlsfMsgs.Ring> _repeated_rings_codec
        = pb::FieldCodec.ForMessage(10, global::LlsfMsgs.Ring.Parser);
    private readonly pbc::RepeatedField<global::LlsfMsgs.Ring> rings_ = new pbc::RepeatedField<global::LlsfMsgs.Ring>();
    /// <summary>
    /// List of all known pucks
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::LlsfMsgs.Ring> Rings {
      get { return rings_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RingInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RingInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!rings_.Equals(other.rings_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= rings_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      rings_.WriteTo(output, _repeated_rings_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += rings_.CalculateSize(_repeated_rings_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RingInfo other) {
      if (other == null) {
        return;
      }
      rings_.Add(other.rings_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            rings_.AddEntriesFrom(input, _repeated_rings_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the RingInfo message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum CompType {
        [pbr::OriginalName("COMP_ID")] CompId = 2000,
        [pbr::OriginalName("MSG_TYPE")] MsgType = 110,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
