// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SimTimeSync.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LlsfMsgs {

  /// <summary>Holder for reflection information generated from SimTimeSync.proto</summary>
  public static partial class SimTimeSyncReflection {

    #region Descriptor
    /// <summary>File descriptor for SimTimeSync.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SimTimeSyncReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFTaW1UaW1lU3luYy5wcm90bxIJbGxzZl9tc2dzGgpUaW1lLnByb3RvIoMB",
            "CgtTaW1UaW1lU3luYxIhCghzaW1fdGltZRgBIAIoCzIPLmxsc2ZfbXNncy5U",
            "aW1lEhgKEHJlYWxfdGltZV9mYWN0b3IYAiACKAISDgoGcGF1c2VkGAMgAigI",
            "IicKCENvbXBUeXBlEgwKB0NPTVBfSUQQ0A8SDQoITVNHX1RZUEUQxwJCNAof",
            "b3JnLnJvYm9jdXBfbG9naXN0aWNzLmxsc2ZfbXNnc0IRU2ltVGltZVN5bmNQ",
            "cm90b3M="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Llsfmsgs.TimeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::LlsfMsgs.SimTimeSync), global::LlsfMsgs.SimTimeSync.Parser, new[]{ "SimTime", "RealTimeFactor", "Paused" }, null, new[]{ typeof(global::LlsfMsgs.SimTimeSync.Types.CompType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SimTimeSync : pb::IMessage<SimTimeSync> {
    private static readonly pb::MessageParser<SimTimeSync> _parser = new pb::MessageParser<SimTimeSync>(() => new SimTimeSync());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SimTimeSync> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LlsfMsgs.SimTimeSyncReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SimTimeSync() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SimTimeSync(SimTimeSync other) : this() {
      _hasBits0 = other._hasBits0;
      simTime_ = other.simTime_ != null ? other.simTime_.Clone() : null;
      realTimeFactor_ = other.realTimeFactor_;
      paused_ = other.paused_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SimTimeSync Clone() {
      return new SimTimeSync(this);
    }

    /// <summary>Field number for the "sim_time" field.</summary>
    public const int SimTimeFieldNumber = 1;
    private global::Llsfmsgs.Time simTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Llsfmsgs.Time SimTime {
      get { return simTime_; }
      set {
        simTime_ = value;
      }
    }

    /// <summary>Field number for the "real_time_factor" field.</summary>
    public const int RealTimeFactorFieldNumber = 2;
    private readonly static float RealTimeFactorDefaultValue = 0F;

    private float realTimeFactor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float RealTimeFactor {
      get { if ((_hasBits0 & 1) != 0) { return realTimeFactor_; } else { return RealTimeFactorDefaultValue; } }
      set {
        _hasBits0 |= 1;
        realTimeFactor_ = value;
      }
    }
    /// <summary>Gets whether the "real_time_factor" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasRealTimeFactor {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "real_time_factor" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearRealTimeFactor() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "paused" field.</summary>
    public const int PausedFieldNumber = 3;
    private readonly static bool PausedDefaultValue = false;

    private bool paused_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Paused {
      get { if ((_hasBits0 & 2) != 0) { return paused_; } else { return PausedDefaultValue; } }
      set {
        _hasBits0 |= 2;
        paused_ = value;
      }
    }
    /// <summary>Gets whether the "paused" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasPaused {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "paused" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearPaused() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SimTimeSync);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SimTimeSync other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SimTime, other.SimTime)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(RealTimeFactor, other.RealTimeFactor)) return false;
      if (Paused != other.Paused) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (simTime_ != null) hash ^= SimTime.GetHashCode();
      if (HasRealTimeFactor) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(RealTimeFactor);
      if (HasPaused) hash ^= Paused.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (simTime_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SimTime);
      }
      if (HasRealTimeFactor) {
        output.WriteRawTag(21);
        output.WriteFloat(RealTimeFactor);
      }
      if (HasPaused) {
        output.WriteRawTag(24);
        output.WriteBool(Paused);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (simTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SimTime);
      }
      if (HasRealTimeFactor) {
        size += 1 + 4;
      }
      if (HasPaused) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SimTimeSync other) {
      if (other == null) {
        return;
      }
      if (other.simTime_ != null) {
        if (simTime_ == null) {
          SimTime = new global::Llsfmsgs.Time();
        }
        SimTime.MergeFrom(other.SimTime);
      }
      if (other.HasRealTimeFactor) {
        RealTimeFactor = other.RealTimeFactor;
      }
      if (other.HasPaused) {
        Paused = other.Paused;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (simTime_ == null) {
              SimTime = new global::Llsfmsgs.Time();
            }
            input.ReadMessage(SimTime);
            break;
          }
          case 21: {
            RealTimeFactor = input.ReadFloat();
            break;
          }
          case 24: {
            Paused = input.ReadBool();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the SimTimeSync message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum CompType {
        [pbr::OriginalName("COMP_ID")] CompId = 2000,
        [pbr::OriginalName("MSG_TYPE")] MsgType = 327,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
