// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Time.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Llsfmsgs {

  /// <summary>Holder for reflection information generated from Time.proto</summary>
  public static partial class TimeReflection {

    #region Descriptor
    /// <summary>File descriptor for Time.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TimeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpUaW1lLnByb3RvEglsbHNmX21zZ3MiIQoEVGltZRILCgNzZWMYASACKAMS",
            "DAoEbnNlYxgCIAIoA0I4Ch9vcmcucm9ib2N1cF9sb2dpc3RpY3MubGxzZl9t",
            "c2dzQgpUaW1lUHJvdG9zqgIITGxzZm1zZ3M="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Llsfmsgs.Time), global::Llsfmsgs.Time.Parser, new[]{ "Sec", "Nsec" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Time stamp and duration structure.
  /// Can be used for absolute times or
  /// durations alike.
  /// </summary>
  public sealed partial class Time : pb::IMessage<Time> {
    private static readonly pb::MessageParser<Time> _parser = new pb::MessageParser<Time>(() => new Time());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Time> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Llsfmsgs.TimeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Time() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Time(Time other) : this() {
      _hasBits0 = other._hasBits0;
      sec_ = other.sec_;
      nsec_ = other.nsec_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Time Clone() {
      return new Time(this);
    }

    /// <summary>Field number for the "sec" field.</summary>
    public const int SecFieldNumber = 1;
    private readonly static long SecDefaultValue = 0L;

    private long sec_;
    /// <summary>
    /// Time in seconds since the Unix epoch
    /// in UTC or seconds part of duration
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Sec {
      get { if ((_hasBits0 & 1) != 0) { return sec_; } else { return SecDefaultValue; } }
      set {
        _hasBits0 |= 1;
        sec_ = value;
      }
    }
    /// <summary>Gets whether the "sec" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasSec {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "sec" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearSec() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "nsec" field.</summary>
    public const int NsecFieldNumber = 2;
    private readonly static long NsecDefaultValue = 0L;

    private long nsec_;
    /// <summary>
    /// Nano seconds after seconds for a time
    /// or nanoseconds part for duration
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Nsec {
      get { if ((_hasBits0 & 2) != 0) { return nsec_; } else { return NsecDefaultValue; } }
      set {
        _hasBits0 |= 2;
        nsec_ = value;
      }
    }
    /// <summary>Gets whether the "nsec" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasNsec {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "nsec" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearNsec() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Time);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Time other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Sec != other.Sec) return false;
      if (Nsec != other.Nsec) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasSec) hash ^= Sec.GetHashCode();
      if (HasNsec) hash ^= Nsec.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (HasSec) {
        output.WriteRawTag(8);
        output.WriteInt64(Sec);
      }
      if (HasNsec) {
        output.WriteRawTag(16);
        output.WriteInt64(Nsec);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasSec) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Sec);
      }
      if (HasNsec) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Nsec);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Time other) {
      if (other == null) {
        return;
      }
      if (other.HasSec) {
        Sec = other.Sec;
      }
      if (other.HasNsec) {
        Nsec = other.Nsec;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Sec = input.ReadInt64();
            break;
          }
          case 16: {
            Nsec = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
