// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Team.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LlsfMsgs {

  /// <summary>Holder for reflection information generated from Team.proto</summary>
  public static partial class TeamReflection {

    #region Descriptor
    /// <summary>File descriptor for Team.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TeamReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpUZWFtLnByb3RvEglsbHNmX21zZ3MqHQoEVGVhbRIICgRDWUFOEAASCwoH",
            "TUFHRU5UQRABQi0KH29yZy5yb2JvY3VwX2xvZ2lzdGljcy5sbHNmX21zZ3NC",
            "ClRlYW1Qcm90b3M="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::LlsfMsgs.Team), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Team identifier.
  /// </summary>
  public enum Team {
    [pbr::OriginalName("CYAN")] Cyan = 0,
    [pbr::OriginalName("MAGENTA")] Magenta = 1,
  }

  #endregion

}

#endregion Designer generated code
