// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Zone.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LlsfMsgs {

  /// <summary>Holder for reflection information generated from Zone.proto</summary>
  public static partial class ZoneReflection {

    #region Descriptor
    /// <summary>File descriptor for Zone.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ZoneReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgpab25lLnByb3RvEglsbHNmX21zZ3MqyQkKBFpvbmUSCQoFQ19aMTgQEhIJ",
            "CgVDX1oyOBAcEgkKBUNfWjM4ECYSCQoFQ19aNDgQMBIJCgVDX1o1OBA6EgkK",
            "BUNfWjY4EEQSCQoFQ19aNzgQThIJCgVDX1oxNxAREgkKBUNfWjI3EBsSCQoF",
            "Q19aMzcQJRIJCgVDX1o0NxAvEgkKBUNfWjU3EDkSCQoFQ19aNjcQQxIJCgVD",
            "X1o3NxBNEgkKBUNfWjE2EBASCQoFQ19aMjYQGhIJCgVDX1ozNhAkEgkKBUNf",
            "WjQ2EC4SCQoFQ19aNTYQOBIJCgVDX1o2NhBCEgkKBUNfWjc2EEwSCQoFQ19a",
            "MTUQDxIJCgVDX1oyNRAZEgkKBUNfWjM1ECMSCQoFQ19aNDUQLRIJCgVDX1o1",
            "NRA3EgkKBUNfWjY1EEESCQoFQ19aNzUQSxIJCgVDX1oxNBAOEgkKBUNfWjI0",
            "EBgSCQoFQ19aMzQQIhIJCgVDX1o0NBAsEgkKBUNfWjU0EDYSCQoFQ19aNjQQ",
            "QBIJCgVDX1o3NBBKEgkKBUNfWjEzEA0SCQoFQ19aMjMQFxIJCgVDX1ozMxAh",
            "EgkKBUNfWjQzECsSCQoFQ19aNTMQNRIJCgVDX1o2MxA/EgkKBUNfWjczEEkS",
            "CQoFQ19aMTIQDBIJCgVDX1oyMhAWEgkKBUNfWjMyECASCQoFQ19aNDIQKhIJ",
            "CgVDX1o1MhA0EgkKBUNfWjYyED4SCQoFQ19aNzIQSBIJCgVDX1oxMRALEgkK",
            "BUNfWjIxEBUSCQoFQ19aMzEQHxIJCgVDX1o0MRApEgoKBU1fWjE4EPoHEgoK",
            "BU1fWjI4EIQIEgoKBU1fWjM4EI4IEgoKBU1fWjQ4EJgIEgoKBU1fWjU4EKII",
            "EgoKBU1fWjY4EKwIEgoKBU1fWjc4ELYIEgoKBU1fWjE3EPkHEgoKBU1fWjI3",
            "EIMIEgoKBU1fWjM3EI0IEgoKBU1fWjQ3EJcIEgoKBU1fWjU3EKEIEgoKBU1f",
            "WjY3EKsIEgoKBU1fWjc3ELUIEgoKBU1fWjE2EPgHEgoKBU1fWjI2EIIIEgoK",
            "BU1fWjM2EIwIEgoKBU1fWjQ2EJYIEgoKBU1fWjU2EKAIEgoKBU1fWjY2EKoI",
            "EgoKBU1fWjc2ELQIEgoKBU1fWjE1EPcHEgoKBU1fWjI1EIEIEgoKBU1fWjM1",
            "EIsIEgoKBU1fWjQ1EJUIEgoKBU1fWjU1EJ8IEgoKBU1fWjY1EKkIEgoKBU1f",
            "Wjc1ELMIEgoKBU1fWjE0EPYHEgoKBU1fWjI0EIAIEgoKBU1fWjM0EIoIEgoK",
            "BU1fWjQ0EJQIEgoKBU1fWjU0EJ4IEgoKBU1fWjY0EKgIEgoKBU1fWjc0ELII",
            "EgoKBU1fWjEzEPUHEgoKBU1fWjIzEP8HEgoKBU1fWjMzEIkIEgoKBU1fWjQz",
            "EJMIEgoKBU1fWjUzEJ0IEgoKBU1fWjYzEKcIEgoKBU1fWjczELEIEgoKBU1f",
            "WjEyEPQHEgoKBU1fWjIyEP4HEgoKBU1fWjMyEIgIEgoKBU1fWjQyEJIIEgoK",
            "BU1fWjUyEJwIEgoKBU1fWjYyEKYIEgoKBU1fWjcyELAIEgoKBU1fWjExEPMH",
            "EgoKBU1fWjIxEP0HEgoKBU1fWjMxEIcIEgoKBU1fWjQxEJEIQi0KH29yZy5y",
            "b2JvY3VwX2xvZ2lzdGljcy5sbHNmX21zZ3NCClpvbmVQcm90b3M="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::LlsfMsgs.Zone), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Zone identifiers
  /// </summary>
  public enum Zone {
    [pbr::OriginalName("C_Z18")] CZ18 = 18,
    [pbr::OriginalName("C_Z28")] CZ28 = 28,
    [pbr::OriginalName("C_Z38")] CZ38 = 38,
    [pbr::OriginalName("C_Z48")] CZ48 = 48,
    [pbr::OriginalName("C_Z58")] CZ58 = 58,
    [pbr::OriginalName("C_Z68")] CZ68 = 68,
    [pbr::OriginalName("C_Z78")] CZ78 = 78,
    [pbr::OriginalName("C_Z17")] CZ17 = 17,
    [pbr::OriginalName("C_Z27")] CZ27 = 27,
    [pbr::OriginalName("C_Z37")] CZ37 = 37,
    [pbr::OriginalName("C_Z47")] CZ47 = 47,
    [pbr::OriginalName("C_Z57")] CZ57 = 57,
    [pbr::OriginalName("C_Z67")] CZ67 = 67,
    [pbr::OriginalName("C_Z77")] CZ77 = 77,
    [pbr::OriginalName("C_Z16")] CZ16 = 16,
    [pbr::OriginalName("C_Z26")] CZ26 = 26,
    [pbr::OriginalName("C_Z36")] CZ36 = 36,
    [pbr::OriginalName("C_Z46")] CZ46 = 46,
    [pbr::OriginalName("C_Z56")] CZ56 = 56,
    [pbr::OriginalName("C_Z66")] CZ66 = 66,
    [pbr::OriginalName("C_Z76")] CZ76 = 76,
    [pbr::OriginalName("C_Z15")] CZ15 = 15,
    [pbr::OriginalName("C_Z25")] CZ25 = 25,
    [pbr::OriginalName("C_Z35")] CZ35 = 35,
    [pbr::OriginalName("C_Z45")] CZ45 = 45,
    [pbr::OriginalName("C_Z55")] CZ55 = 55,
    [pbr::OriginalName("C_Z65")] CZ65 = 65,
    [pbr::OriginalName("C_Z75")] CZ75 = 75,
    [pbr::OriginalName("C_Z14")] CZ14 = 14,
    [pbr::OriginalName("C_Z24")] CZ24 = 24,
    [pbr::OriginalName("C_Z34")] CZ34 = 34,
    [pbr::OriginalName("C_Z44")] CZ44 = 44,
    [pbr::OriginalName("C_Z54")] CZ54 = 54,
    [pbr::OriginalName("C_Z64")] CZ64 = 64,
    [pbr::OriginalName("C_Z74")] CZ74 = 74,
    [pbr::OriginalName("C_Z13")] CZ13 = 13,
    [pbr::OriginalName("C_Z23")] CZ23 = 23,
    [pbr::OriginalName("C_Z33")] CZ33 = 33,
    [pbr::OriginalName("C_Z43")] CZ43 = 43,
    [pbr::OriginalName("C_Z53")] CZ53 = 53,
    [pbr::OriginalName("C_Z63")] CZ63 = 63,
    [pbr::OriginalName("C_Z73")] CZ73 = 73,
    [pbr::OriginalName("C_Z12")] CZ12 = 12,
    [pbr::OriginalName("C_Z22")] CZ22 = 22,
    [pbr::OriginalName("C_Z32")] CZ32 = 32,
    [pbr::OriginalName("C_Z42")] CZ42 = 42,
    [pbr::OriginalName("C_Z52")] CZ52 = 52,
    [pbr::OriginalName("C_Z62")] CZ62 = 62,
    [pbr::OriginalName("C_Z72")] CZ72 = 72,
    [pbr::OriginalName("C_Z11")] CZ11 = 11,
    [pbr::OriginalName("C_Z21")] CZ21 = 21,
    [pbr::OriginalName("C_Z31")] CZ31 = 31,
    [pbr::OriginalName("C_Z41")] CZ41 = 41,
    [pbr::OriginalName("M_Z18")] MZ18 = 1018,
    [pbr::OriginalName("M_Z28")] MZ28 = 1028,
    [pbr::OriginalName("M_Z38")] MZ38 = 1038,
    [pbr::OriginalName("M_Z48")] MZ48 = 1048,
    [pbr::OriginalName("M_Z58")] MZ58 = 1058,
    [pbr::OriginalName("M_Z68")] MZ68 = 1068,
    [pbr::OriginalName("M_Z78")] MZ78 = 1078,
    [pbr::OriginalName("M_Z17")] MZ17 = 1017,
    [pbr::OriginalName("M_Z27")] MZ27 = 1027,
    [pbr::OriginalName("M_Z37")] MZ37 = 1037,
    [pbr::OriginalName("M_Z47")] MZ47 = 1047,
    [pbr::OriginalName("M_Z57")] MZ57 = 1057,
    [pbr::OriginalName("M_Z67")] MZ67 = 1067,
    [pbr::OriginalName("M_Z77")] MZ77 = 1077,
    [pbr::OriginalName("M_Z16")] MZ16 = 1016,
    [pbr::OriginalName("M_Z26")] MZ26 = 1026,
    [pbr::OriginalName("M_Z36")] MZ36 = 1036,
    [pbr::OriginalName("M_Z46")] MZ46 = 1046,
    [pbr::OriginalName("M_Z56")] MZ56 = 1056,
    [pbr::OriginalName("M_Z66")] MZ66 = 1066,
    [pbr::OriginalName("M_Z76")] MZ76 = 1076,
    [pbr::OriginalName("M_Z15")] MZ15 = 1015,
    [pbr::OriginalName("M_Z25")] MZ25 = 1025,
    [pbr::OriginalName("M_Z35")] MZ35 = 1035,
    [pbr::OriginalName("M_Z45")] MZ45 = 1045,
    [pbr::OriginalName("M_Z55")] MZ55 = 1055,
    [pbr::OriginalName("M_Z65")] MZ65 = 1065,
    [pbr::OriginalName("M_Z75")] MZ75 = 1075,
    [pbr::OriginalName("M_Z14")] MZ14 = 1014,
    [pbr::OriginalName("M_Z24")] MZ24 = 1024,
    [pbr::OriginalName("M_Z34")] MZ34 = 1034,
    [pbr::OriginalName("M_Z44")] MZ44 = 1044,
    [pbr::OriginalName("M_Z54")] MZ54 = 1054,
    [pbr::OriginalName("M_Z64")] MZ64 = 1064,
    [pbr::OriginalName("M_Z74")] MZ74 = 1074,
    [pbr::OriginalName("M_Z13")] MZ13 = 1013,
    [pbr::OriginalName("M_Z23")] MZ23 = 1023,
    [pbr::OriginalName("M_Z33")] MZ33 = 1033,
    [pbr::OriginalName("M_Z43")] MZ43 = 1043,
    [pbr::OriginalName("M_Z53")] MZ53 = 1053,
    [pbr::OriginalName("M_Z63")] MZ63 = 1063,
    [pbr::OriginalName("M_Z73")] MZ73 = 1073,
    [pbr::OriginalName("M_Z12")] MZ12 = 1012,
    [pbr::OriginalName("M_Z22")] MZ22 = 1022,
    [pbr::OriginalName("M_Z32")] MZ32 = 1032,
    [pbr::OriginalName("M_Z42")] MZ42 = 1042,
    [pbr::OriginalName("M_Z52")] MZ52 = 1052,
    [pbr::OriginalName("M_Z62")] MZ62 = 1062,
    [pbr::OriginalName("M_Z72")] MZ72 = 1072,
    [pbr::OriginalName("M_Z11")] MZ11 = 1011,
    [pbr::OriginalName("M_Z21")] MZ21 = 1021,
    [pbr::OriginalName("M_Z31")] MZ31 = 1031,
    [pbr::OriginalName("M_Z41")] MZ41 = 1041,
  }

  #endregion

}

#endregion Designer generated code
