# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET build and test

on:
  push:
    branches: [ "master", "mqtt-test" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Start Mosquitto
      uses: namoshek/mosquitto-github-action@v1
      with:
        version: '1.6'
        ports: '1883:1883'
        container-name: 'mosquitto'
        config: ${{ github.workspace }}/.github/workflows/mosquitto.conf
    - name: Test
      run: dotnet test Simulatortests/Simulatortests.csproj --no-build --verbosity normal 